//! Verify discovered package-manager commands in the actual isolated runtime.
use crow::execution::Execution;
use serde_json::{Value, json};
use std::{path::Path, process::Command};
use tokio_util::sync::CancellationToken;

fn git(path: &Path, args: &[&str]) -> String {
    let out = Command::new("git")
        .arg("-C")
        .arg(path)
        .args(args)
        .env("GIT_CONFIG_GLOBAL", "/dev/null")
        .env("GIT_CONFIG_NOSYSTEM", "1")
        .env("GIT_AUTHOR_NAME", "Test")
        .env("GIT_AUTHOR_EMAIL", "test@example.invalid")
        .env("GIT_COMMITTER_NAME", "Test")
        .env("GIT_COMMITTER_EMAIL", "test@example.invalid")
        .output()
        .unwrap();
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    String::from_utf8(out.stdout).unwrap().trim().into()
}
async fn call(exec: &Execution, name: &str, args: Value) -> Value {
    exec.call(name, &args, CancellationToken::new())
        .await
        .unwrap()
}

#[tokio::test]
#[ignore = "requires rootless Podman, the managed toolchain and public npm registry access"]
async fn discovered_pinned_managers_and_nested_commands_run_offline() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join(".crow-data/autonomous-runtime-test");
    std::fs::create_dir_all(&root).unwrap();
    for (manager, version, lockfile, lock) in [
        (
            "npm",
            "10.9.0",
            "package-lock.json",
            r#"{"name":"crow-discovery-fixture","version":"1.0.0","lockfileVersion":3,"requires":true,"packages":{"":{"name":"crow-discovery-fixture","version":"1.0.0","hasInstallScript":true}}}"#,
        ),
        (
            "pnpm",
            "9.15.4",
            "pnpm-lock.yaml",
            "lockfileVersion: '9.0'\nsettings:\n  autoInstallPeers: true\n  excludeLinksFromLockfile: false\nimporters:\n  .: {}\n",
        ),
        (
            "yarn",
            "4.9.2",
            "yarn.lock",
            "# This file is generated by running \"yarn install\" inside your project.\n# Manual changes might be lost - proceed with caution!\n\n__metadata:\n  version: 8\n  cacheKey: 10c0\n\n\"crow-discovery-fixture@workspace:.\":\n  version: 0.0.0-use.local\n  resolution: \"crow-discovery-fixture@workspace:.\"\n  languageName: unknown\n  linkType: soft\n",
        ),
    ] {
        let temp = tempfile::tempdir_in(&root).unwrap();
        let repo = temp.path().join("repo");
        std::fs::create_dir(&repo).unwrap();
        git(&repo, &["init", "-b", "main"]);
        let mut scripts = json!({"test":"node test.cjs", "start":"node test.cjs"});
        if manager == "npm" {
            // This checks the installation lifecycle as well as later test/start
            // shells. An absolute npm entrypoint alone leaves nested npm on PATH.
            scripts["postinstall"] = json!("node test.cjs");
        }
        std::fs::write(repo.join("package.json"), json!({"name":"crow-discovery-fixture","version":"1.0.0","private":true,"packageManager":format!("{manager}@{version}"),"scripts":scripts}).to_string()).unwrap();
        std::fs::write(repo.join(lockfile), lock).unwrap();
        std::fs::write(repo.join("test.cjs"), format!("const assert=require('node:assert/strict'); const {{execFileSync}}=require('node:child_process'); assert(process.env.npm_config_user_agent.includes('{manager}/{version}')); assert.equal(execFileSync('{manager}', ['--version'], {{encoding:'utf8'}}).trim(), '{version}'); console.log('verified {manager}/{version} including nested command');\n")).unwrap();
        git(&repo, &["add", "."]);
        git(&repo, &["commit", "-m", "package manager fixture"]);
        let commit = git(&repo, &["rev-parse", "HEAD"]);
        let config = json!({"podman":std::env::var("CROW_TEST_PODMAN").unwrap_or("podman".into()),"automatic":true});
        let context = json!({"root":root,"job":{"repo":"fixture/discovery","settings":{"execution":config}},"source":{"dir":repo,"head":commit,"base":commit}});
        let exec = Execution::from_context(&context, &temp.path().join("experiments"))
            .unwrap()
            .unwrap();
        let found = call(&exec, "discover_environment", json!({"revision":"head"})).await;
        let project = &found["projects"][0];
        let setup = call(
            &exec,
            "prepare_environment",
            json!({"revision":"head","setup":project["setup"]}),
        )
        .await;
        assert_eq!(setup["status"], "passed", "{manager} preparation: {setup}");
        if manager == "npm" {
            assert!(
                setup["stdout"].as_str().unwrap().contains(&format!(
                    "verified {manager}/{version} including nested command"
                )),
                "npm lifecycle probe did not run: {setup}"
            );
        }
        let result = call(
            &exec,
            "run_experiment",
            json!({"revision":"head","environment":setup["id"],"command":format!("{} && {}", project["test"].as_str().unwrap(), project["start"].as_str().unwrap())}),
        )
        .await;
        assert_eq!(result["status"], "passed", "{manager} test: {result}");
        assert!(result["stdout"].as_str().unwrap().contains(&format!(
            "verified {manager}/{version} including nested command"
        )));
        println!(
            "Discovered {manager}@{version}: setup passed; pinned manager ran test/start and nested commands offline."
        );
    }
}
